print("Hello World")
print("First Commit")
print("Second Commit")
print("Git Diff")
print("Git Restore")
print("New branch")
print("merge conflict 1")
print('merge conflict 2')
print('git remote merge')
